name = "listentogether"
main = "listen-together-worker.js"
compatibility_date = "2026-05-24"

account_id = "eb8b00d08be5a035fea4227f295b7eb7"

[[durable_objects.bindings]]
name = "LISTEN_TOGETHER_SESSION"
class_name = "ListenTogetherSession"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ListenTogetherSession"]
